# Generated by Django 6.0.4 on 2026-04-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='accounts.player')),
            ],
        ),
        migrations.CreateModel(
            name='BuildModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_type', models.CharField(choices=[('min_bpm', 'Minimum BPM'), ('max_ar', 'Maximum AR'), ('min_ar', 'Minimum AR'), ('min_accuracy', 'Minimum Accuracy'), ('mod_includes', 'Mod Includes'), ('min_star_rating', 'Minimum Star Rating'), ('max_star_rating', 'Maximum Star Rating')], max_length=50)),
                ('modifier_value', models.CharField(max_length=100)),
                ('bonus_multiplier', models.FloatField()),
                ('order', models.PositiveIntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='builds.build')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
