# Generated by Django 6.0.4 on 2026-04-12 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quest_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('progression', 'Progression')], max_length=20)),
                ('category', models.CharField(choices=[('performance', 'Performance'), ('consistency', 'Consistency'), ('exploration', 'Exploration'), ('challenge', 'Challenge')], max_length=20)),
                ('condition_type', models.CharField(choices=[('min_star_rating', 'Minimum Star Rating'), ('min_accuracy', 'Minimum Accuracy'), ('map_passed', 'Map Passed'), ('unique_mapper', 'Unique Mapper'), ('above_skill_baseline', 'Above Skill Baseline'), ('below_skill_baseline', 'Below Skill Baseline'), ('min_score', 'Minimum Score'), ('mod_includes', 'Mod Includes'), ('min_bpm', 'Minimum BPM')], max_length=50)),
                ('condition_value', models.CharField(max_length=100)),
                ('condition_operator', models.CharField(choices=[('gte', 'Greater than or equal'), ('lte', 'Less than or equal'), ('eq', 'Equal to'), ('gt', 'Greater than'), ('lt', 'Less than')], max_length=10)),
                ('required_count', models.PositiveIntegerField(default=1)),
                ('timeframe', models.CharField(choices=[('daily', 'Today'), ('weekly', 'This week'), ('alltime', 'All time')], max_length=20)),
                ('scales_with_baseline', models.BooleanField(default=False)),
                ('is_repeatable', models.BooleanField(default=False)),
                ('xp_reward', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='active', max_length=20)),
                ('is_archived', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progresses', to='accounts.player')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='quests.quest')),
            ],
        ),
        migrations.CreateModel(
            name='QuestProgressPlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('play', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameplay.play')),
                ('quest_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.questprogress')),
            ],
            options={
                'unique_together': {('quest_progress', 'play')},
            },
        ),
        migrations.AddField(
            model_name='questprogress',
            name='qualifying_plays',
            field=models.ManyToManyField(related_name='quest_progresses', through='quests.QuestProgressPlay', to='gameplay.play'),
        ),
        migrations.AddConstraint(
            model_name='questprogress',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('player', 'quest'), name='unique_active_quest_progress'),
        ),
    ]
