# Generated by Django 6.0.4 on 2026-04-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='condition_type',
            field=models.CharField(choices=[('min_star_rating', 'Minimum Star Rating'), ('min_accuracy', 'Minimum Accuracy'), ('map_passed', 'Map Passed'), ('unique_mapper', 'Unique Mapper'), ('above_skill_baseline', 'Above Skill Baseline'), ('below_skill_baseline', 'Below Skill Baseline'), ('min_score', 'Minimum Score'), ('min_pp', 'Minimum PP'), ('beatmap_personal_best_pp', 'Beatmap Personal Best PP'), ('mod_includes', 'Mod Includes'), ('min_bpm', 'Minimum BPM')], max_length=50),
        ),
    ]
