# Generated by Django 6.0.4 on 2026-04-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_player_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
