# Generated by Django 6.0.4 on 2026-04-12 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('builds', '0001_initial'),
        ('gameplay', '0001_initial'),
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BossChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('lore_text', models.TextField()),
                ('xp_reward', models.PositiveIntegerField()),
                ('attempts_allowed', models.PositiveIntegerField(blank=True, null=True)),
                ('scales_with_baseline', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lore_text', models.TextField()),
                ('order', models.PositiveIntegerField(unique=True)),
                ('skill_focus', models.CharField(max_length=100)),
                ('minimum_level', models.PositiveIntegerField(default=1)),
                ('is_final', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='BossChallengeCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('min_star_rating', 'Minimum Star Rating'), ('min_accuracy', 'Minimum Accuracy'), ('map_passed', 'Map Passed'), ('above_skill_baseline', 'Above Skill Baseline'), ('min_score', 'Minimum Score'), ('mod_includes', 'Mod Includes'), ('min_combo', 'Minimum Combo')], max_length=50)),
                ('condition_value', models.CharField(max_length=100)),
                ('condition_operator', models.CharField(choices=[('gte', 'Greater than or equal'), ('lte', 'Less than or equal'), ('eq', 'Equal to'), ('gt', 'Greater than'), ('lt', 'Less than')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('boss_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='progression.bosschallenge')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='bosschallenge',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boss_challenge', to='progression.region'),
        ),
        migrations.CreateModel(
            name='XPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_xp', models.PositiveIntegerField()),
                ('final_xp', models.PositiveIntegerField()),
                ('source_type', models.CharField(choices=[('play', 'Play'), ('quest', 'Quest'), ('boss', 'Boss Challenge')], max_length=20)),
                ('source_id', models.PositiveIntegerField()),
                ('modifier_breakdown', models.JSONField(default=list)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('active_build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='xp_logs', to='builds.build')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_logs', to='accounts.player')),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerBossChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='locked', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('boss_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_attempts', to='progression.bosschallenge')),
                ('completion_play', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boss_completions', to='gameplay.play')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boss_challenges', to='accounts.player')),
            ],
            options={
                'unique_together': {('player', 'boss_challenge')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('active', 'Active'), ('completed', 'Completed')], default='locked', max_length=20)),
                ('entered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_regions', to='accounts.player')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_regions', to='progression.region')),
            ],
            options={
                'unique_together': {('player', 'region')},
            },
        ),
        migrations.CreateModel(
            name='RegionQuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_quests', to='quests.quest')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_quests', to='progression.region')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('region', 'quest')},
            },
        ),
    ]
