# Generated by Django 6.0.4 on 2026-04-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beatmap_id', models.IntegerField(unique=True)),
                ('beatmapset_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('mapper', models.CharField(max_length=255)),
                ('star_rating', models.FloatField()),
                ('bpm', models.FloatField()),
                ('length_seconds', models.IntegerField()),
                ('ar', models.FloatField()),
                ('od', models.FloatField()),
                ('cs', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osu_score_id', models.BigIntegerField(unique=True)),
                ('accuracy', models.FloatField()),
                ('score', models.BigIntegerField()),
                ('max_combo', models.IntegerField()),
                ('passed', models.BooleanField()),
                ('mods', models.JSONField(default=list)),
                ('adjusted_star_rating', models.FloatField()),
                ('played_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beatmap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='gameplay.beatmap')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='accounts.player')),
            ],
        ),
    ]
