# Generated by Django 6.0.4 on 2026-04-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beatmap',
            name='cover_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='beatmap',
            name='version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='play',
            name='pp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='play',
            name='rank',
            field=models.CharField(default='F', max_length=5),
        ),
    ]
