# Generated by Django 6.0.4 on 2026-04-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0002_beatmap_cover_url_beatmap_version_play_pp_play_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='adjusted_star_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
